### PR TITLE
Added two lines in Dockerfile to support wget command.

### PR DESCRIPTION
**Pull request by milancimbaljevic**
CONFIG_CMD_WGET=y
CONFIG_PROT_TCP_SACK=y

### CODE REVIEW

**Comment by dmikushin** [comment]
@milancimbaljevic as you said the command is recognized, I'm going to test this on the real embedded board right away. There I have a network. Meanwhile, you can get the network support for Qemu and also share it with us :+1:

**Comment by milancimbaljevic** [comment]
@dmikushin Hi, thanks for trying it out. I will share my results.
Did it work?

**Comment by dmikushin** [comment]
> Did it work?

Yes, it works!

```
=> wget google.com
Speed: 1000, full duplex
HTTP/1.1 400 Bad Request
Packets received 4, Transfer Successful
```

**Comment by dmikushin** [comment]
Pushed in 5c867a47bd40de11f6b4011f765479ab581fe9a8 , thanks!

**Pull request closed without merging**
